Update CY scripts to run on docker container
cortezaproject/corteza-e2e-cypress pull request #98
Opened 2023-12-22 15:44 UTC by kelanik8

2024-01-03 09:58 UTC, petergrlica requested changes

2024-01-03 09:58 UTC, petergrlica commented on .github/workflows/test.yml
>  on:
Remove this file, the tests will be running on `corteza` repo, not this one

2024-01-03 09:58 UTC, petergrlica commented on docker-compose.yaml
> +    image: cortezaproject/corteza:2023.3.4
why `2023.3.4`? is the corteza service still needed?

2024-01-04 14:25 UTC, merged

2024-01-05 08:21 UTC, katrinDY commented on cypress/e2e/basic-functionalities/admin/user/Create.cy.js
> +const email = Cypress.env('USER_EMAIL')
In the previous test, you created a user and were logged in with his credentials. Why do you need to log in again here?

2024-01-05 08:21 UTC, katrinDY commented on .github/workflows/test.yml
> +      - 2023.9.x-feature-e2e
Don't forget to change this before merging

2024-01-05 08:25 UTC, kelanik8 commented on cypress/e2e/basic-functionalities/admin/user/Create.cy.js
> +const email = Cypress.env('USER_EMAIL')
when running the tests in parrallel on GH action, it's required to be logged in again because the previous auth session is destroyed